include:
  - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/$DOCKER_ROS_GIT_REF/.gitlab-ci/docker-ros.yml

variables:
  BASE_IMAGE: rwthika/ros2:jazzy
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  COMMAND: ros2 topic list
  PLATFORM: amd64,arm64
  TARGET: dev,run
  BUILD_CONTEXT: ros2
  IMAGE_TAG: ros2
  ENABLE_INDUSTRIAL_CI: 'true'
