x-base-image: &base-image BASE_IMAGE  # e.g. gitlab.ika.rwth-aachen.de:5050/fb-fi/ops/docker-base/ros2:latest
x-dev-image:  &dev-image  DEV_IMAGE   # e.g. gitlab.ika.rwth-aachen.de:5050/fb-fi/ops/hello_world:latest-dev
x-run-image:  &run-image  RUN_IMAGE   # e.g. gitlab.ika.rwth-aachen.de:5050/fb-fi/ops/hello_world:latest
x-command:    &command    COMMAND     # e.g. ros2 topic pub "/ping" "std_msgs/msg/String" "{data: Hello World}"

# ==============================================================================

x-build: &build
  dockerfile: ./docker/docker-ros/Dockerfile
  context: ../
  args:
    BASE_IMAGE: *base-image
    COMMAND: *command
    GIT_HTTPS_USER: $GIT_HTTPS_USER
    GIT_HTTPS_PASSWORD: $GIT_HTTPS_PASSWORD

services:
  dev:
    image: *dev-image
    build:
      target: dev
      <<: *build
  run:
    image: *run-image
    build:
      target: run
      <<: *build
