on:
  push:
    branches-ignore:
      - '*'
  workflow_dispatch:
    inputs:
      docker-ros-git-ref:
        description: "docker-ros Git reference"
        default: main

jobs:
  docker-ros-basic:
    runs-on: ubuntu-latest
    name: docker-ros-basic
    steps:
      - name: docker-ros
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ika-rwth-aachen/docker-ros@${{ github.event.inputs.docker-ros-git-ref }}
          with: '{ "base-image": "ros:rolling-ros-core", "command": "ros2 topic list", "platform": "amd64", "target": "dev,run", "build-context": "ros2", "tag": "ros2", "enable-industrial-ci": "true"}'
      - name: docker-ros
        if: ${{ github.event_name == 'push' }}
        uses: ika-rwth-aachen/docker-ros@feature/github-action
        with:
          base-image: ros:rolling-ros-core
          command: ros2 topic list
          platform: amd64
          target: dev,run
          build-context: ros2
          tag: ros2
          enable-industrial-ci: true
  docker-ros-advanced:
    name: docker-ros-advanced
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [dev, run]
        platform: [amd64, arm64]  
    steps:
      - name: docker-ros
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ika-rwth-aachen/docker-ros@${{ github.event.inputs.docker-ros-git-ref }}
          with: '{ "base-image": "ros:rolling-ros-core", "command": "ros2 topic list", "platform": "${{ matrix.platform }}", "target": "${{ matrix.target }}", "build-context": "ros2", "tag": "ros2", "enable-industrial-ci": "true", "enable-singlearch-push": "true",}'
      - name: docker-ros
        if: ${{ github.event_name == 'push' }}
        uses: ika-rwth-aachen/docker-ros@feature/github-action
        with:
          base-image: ros:rolling-ros-core
          command: ros2 topic list
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}
          build-context: ros2
          tag: ros2
          enable-industrial-ci: true
          enable-singlearch-push: true