name: ROS

on:
  push:
    branches-ignore:
      - '*'
  workflow_dispatch:
    inputs:
      docker-ros-git-ref:
        description: "docker-ros Git reference"
        default: main

jobs:

  basic:
    name: basic
    runs-on: ubuntu-latest
    steps:

      - name: docker-ros
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ika-rwth-aachen/docker-ros@${{ github.event.inputs.docker-ros-git-ref }}
          with: '{ "base-image": "rwthika/ros:latest", "command": "roscore", "platform": "amd64", "target": "dev,run", "build-context": "ros1", "image-tag": "ros1", "enable-industrial-ci": "true"}'

      - name: docker-ros
        if: ${{ github.event_name == 'push' }}
        uses: ika-rwth-aachen/docker-ros@${{ github.event.inputs.docker-ros-git-ref }}
        with:
          base-image: rwthika/ros:latest
          command: roscore
          platform: amd64,arm64
          target: dev,run
          build-context: ros1
          image-tag: ros1
          enable-industrial-ci: true

  advanced:
    name: advanced
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [dev, run]
        platform: [amd64, arm64]  
    steps:

      - name: docker-ros
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ika-rwth-aachen/docker-ros@${{ github.event.inputs.docker-ros-git-ref }}
          with: '{ "base-image": "rwthika/ros:latest", "command": "roscore", "platform": "${{ matrix.platform }}", "target": "${{ matrix.target }}", "build-context": "ros1", "tag": "image-ros1", "enable-industrial-ci": "true", "enable-singlearch-push": "true"}'

      - name: docker-ros
        if: ${{ github.event_name == 'push' }}
        uses: ika-rwth-aachen/docker-ros@${{ github.event.inputs.docker-ros-git-ref }}
        with:
          base-image: rwthika/ros:latest
          command: roscore
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}
          build-context: ros1
          image-tag: ros1
          enable-industrial-ci: true
          enable-singlearch-push: true
